"""Production-readiness regression tests for isolation, approval, and graph bounds."""

from __future__ import annotations

import asyncio
from datetime import UTC, datetime
from uuid import UUID, uuid4

import pytest
from pydantic import ValidationError

from art_sim.attack.risk import RiskScorer, RiskScoringSettings
from art_sim.attack.simulated_graph import SimulatedAttackGraph
from art_sim.domain.exceptions import (
    ApprovalRequiredError,
    ConfigurationError,
    TopologyNotFoundError,
)
from art_sim.domain.models import (
    Asset,
    AssetRelationship,
    AssetType,
    Criticality,
    Environment,
    RelationshipType,
    Vulnerability,
)
from art_sim.remediation.approval import HumanApprovalWorkflow, RemediationFlowState
from art_sim.remediation.models import (
    ApprovalDecision,
    ApprovalRecord,
    ApprovalStatus,
    NormalizedRemediation,
)
from art_sim.remediation.normalization import RemediationPlanner
from art_sim.remediation.state_machine import RemediationLifecycle, SimulationLifecycleState
from art_sim.remediation.verification import RemediationVerifier
from art_sim.security.secrets import EnvironmentSecretProvider


def _asset(identifier: int, *, crown: bool = False) -> Asset:
    """Build deterministic shadow-only assets for bounded topology tests."""
    return Asset(
        asset_id=UUID(int=identifier),
        name=f"shadow-{identifier}",
        asset_type=AssetType.DATABASE if crown else AssetType.COMPUTE,
        environment=Environment.SHADOW,
        criticality=Criticality.CRITICAL if crown else Criticality.MEDIUM,
        is_crown_jewel=crown,
        provider="synthetic",
    )


def _relationship(
    source: int, target: int, kind: RelationshipType = RelationshipType.NETWORK_REACHABLE
) -> AssetRelationship:
    """Build one deterministic graph edge with intentionally mutable nested data."""
    return AssetRelationship(
        source_asset_id=UUID(int=source),
        target_asset_id=UUID(int=target),
        relationship_type=kind,
        properties={"origin": "synthetic"},
    )


def _linear_graph() -> SimulatedAttackGraph:
    """Create source -> pivot -> crown graph used across security boundary tests."""
    return SimulatedAttackGraph(
        assets=(_asset(1), _asset(2), _asset(3, crown=True)),
        relationships=(
            _relationship(1, 2, RelationshipType.CONTAINER_ESCAPE),
            _relationship(2, 3, RelationshipType.ACCESS),
        ),
    )


def _proposal(graph: SimulatedAttackGraph) -> tuple[NormalizedRemediation, float]:
    """Produce a real normalized proposal without involving external infrastructure."""
    path = graph.find_shortest_path_to_crown_jewel(UUID(int=1))
    assessment = RiskScorer().assess(path, graph.assets)
    return RemediationPlanner().propose(path, assessment), assessment.score


def test_shadow_graph_fork_is_deep_and_original_graph_is_unchanged() -> None:
    """Nested model maps cannot cross the original/shadow simulation boundary."""
    original = _linear_graph()
    baseline = original.model_dump(mode="json")
    fork = original.fork()
    fork.relationships[0].properties["branch"] = "one"
    modified = fork.with_relationship_properties(fork.relationships[1], {"policy": "deny"})
    removed = modified.without_relationship(modified.relationships[0])

    assert original.model_dump(mode="json") == baseline
    assert "branch" not in original.relationships[0].properties
    assert original.relationships[1].properties == {"origin": "synthetic"}
    assert len(removed.relationships) == 1
    assert len(original.relationships) == 2


async def test_parallel_shadow_branches_and_rollback_are_independent() -> None:
    """Concurrent what-if simulations never share mutable properties or alter rollback data."""
    original = _linear_graph()
    baseline = original.model_dump(mode="json")

    async def run_branch(label: str) -> str:
        shadow = original.fork()
        shadow.relationships[0].properties["branch"] = label
        await asyncio.sleep(0)
        return shadow.relationships[0].properties["branch"]

    results = await asyncio.gather(run_branch("alpha"), run_branch("beta"))
    rollback = original.fork()

    assert tuple(results) == ("alpha", "beta")
    assert original.model_dump(mode="json") == baseline
    assert rollback.model_dump(mode="json") == baseline


async def test_approval_gate_blocks_resume_rejection_and_forged_state() -> None:
    """Only a signed approval generated by this workflow unlocks simulated verification."""
    graph = _linear_graph()
    proposal, score = _proposal(graph)
    workflow = HumanApprovalWorkflow(RemediationVerifier(), approval_secret=b"a" * 32)

    def initial_state(run_id: UUID) -> RemediationFlowState:
        return RemediationFlowState(
            run_id=run_id,
            source_asset_id=UUID(int=1),
            simulated_graph=graph,
            remediation=proposal,
            risk_score=score,
            approval_required=True,
            approval_status=ApprovalStatus.PENDING,
        )

    pending_run = uuid4()
    await workflow.start(initial_state(pending_run))
    with pytest.raises(ApprovalRequiredError):
        await workflow.graph.ainvoke(None, workflow._config(pending_run))

    rejected_run = uuid4()
    await workflow.start(initial_state(rejected_run))
    rejected = await workflow.decide(
        rejected_run,
        decision=ApprovalDecision.REJECTED,
        operator="architect",
        reason="Operational window is closed.",
    )
    assert rejected["approval_status"] is ApprovalStatus.REJECTED
    assert getattr(rejected["lifecycle"], "state", None) is SimulationLifecycleState.REJECTED
    assert "verification_result" not in rejected

    forged_record = ApprovalRecord(
        remediation_id=proposal.remediation_id,
        operator="forged-operator",
        decision=ApprovalDecision.APPROVED,
        risk_score=score,
        reason="forged",
        decided_at=datetime.now(UTC),
    )
    forged = initial_state(uuid4())
    forged["approval_status"] = ApprovalStatus.APPROVED
    forged["approval_record"] = forged_record
    forged["approval_proof"] = "not-a-valid-hmac"
    with pytest.raises(ApprovalRequiredError):
        workflow._verification(forged)


async def test_parallel_decisions_for_one_run_allow_exactly_one_transition() -> None:
    """Competing in-process operators cannot produce an approve/reject split brain."""
    graph = _linear_graph()
    proposal, score = _proposal(graph)
    workflow = HumanApprovalWorkflow(RemediationVerifier(), approval_secret=b"b" * 32)
    run_id = uuid4()
    await workflow.start(
        RemediationFlowState(
            run_id=run_id,
            source_asset_id=UUID(int=1),
            simulated_graph=graph,
            remediation=proposal,
            risk_score=score,
            approval_required=True,
            approval_status=ApprovalStatus.PENDING,
        )
    )

    outcomes = await asyncio.gather(
        workflow.decide(run_id, decision=ApprovalDecision.APPROVED, operator="one", reason="approve"),
        workflow.decide(run_id, decision=ApprovalDecision.REJECTED, operator="two", reason="reject"),
        return_exceptions=True,
    )

    assert sum(isinstance(outcome, ApprovalRequiredError) for outcome in outcomes) == 1
    assert sum(isinstance(outcome, dict) for outcome in outcomes) == 1


def test_human_approval_fails_closed_without_signing_secret() -> None:
    """A missing approval secret cannot silently enable verification."""
    with pytest.raises(ConfigurationError, match="approval_secret"):
        HumanApprovalWorkflow(RemediationVerifier())


def test_environment_secret_provider_fails_closed_and_redacts_value(monkeypatch: pytest.MonkeyPatch) -> None:
    """The local secret adapter neither defaults missing values nor exposes the wrapper value."""
    provider = EnvironmentSecretProvider()
    monkeypatch.delenv("ART_SIM_TEST_SECRET", raising=False)
    with pytest.raises(ConfigurationError, match="ART_SIM_TEST_SECRET"):
        provider.get_secret("ART_SIM_TEST_SECRET")
    monkeypatch.setenv("ART_SIM_TEST_SECRET", "not-for-logs")
    assert str(provider.get_secret("ART_SIM_TEST_SECRET")) == "**********"


def test_lifecycle_forbids_impossible_transitions_and_requires_evidence() -> None:
    """Lifecycle transitions require approval before simulation and proof before verified."""
    lifecycle = RemediationLifecycle()
    with pytest.raises(ValueError, match="Invalid lifecycle transition"):
        lifecycle.transition(SimulationLifecycleState.APPLIED_SIMULATED)

    awaiting = (
        lifecycle.transition(SimulationLifecycleState.ANALYZING)
        .transition(SimulationLifecycleState.REMEDIATION_PENDING)
        .transition(SimulationLifecycleState.AWAITING_APPROVAL)
    )
    with pytest.raises(ValidationError, match="approved lifecycle states"):
        awaiting.transition(SimulationLifecycleState.APPROVED)

    approved = ApprovalRecord(
        remediation_id=uuid4(),
        operator="architect",
        decision=ApprovalDecision.APPROVED,
        risk_score=42.0,
        reason="Approved in test.",
    )
    simulated = awaiting.transition(SimulationLifecycleState.APPROVED, approval=approved).transition(
        SimulationLifecycleState.APPLIED_SIMULATED
    )
    assert simulated.state is SimulationLifecycleState.APPLIED_SIMULATED
    with pytest.raises(ValueError, match="Invalid lifecycle transition"):
        simulated.transition(SimulationLifecycleState.VERIFIED)


def test_cvss_bounds_vector_syntax_and_scoring_settings_are_validated() -> None:
    """Risk inputs reject impossible scores, malformed CVSS, and negative weights."""
    with pytest.raises(ValidationError):
        Vulnerability(
            title="Synthetic issue",
            severity=Criticality.HIGH,
            cvss_score=10.1,
            affected_asset_id=UUID(int=1),
        )
    with pytest.raises(ValidationError):
        Vulnerability(
            title="Synthetic issue",
            severity=Criticality.HIGH,
            cvss_score=7.5,
            cvss_vector="ignore prior instructions",
            affected_asset_id=UUID(int=1),
        )
    valid = Vulnerability(
        title="Synthetic issue",
        severity=Criticality.HIGH,
        cvss_score=7.5,
        cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N",
        affected_asset_id=UUID(int=1),
    )
    assert valid.cvss_score == 7.5
    with pytest.raises(ValidationError):
        RiskScoringSettings(cvss_weight=-0.1)


def test_path_search_handles_cycles_density_multiple_crowns_and_depth_limit() -> None:
    """BFS terminates deterministically and respects the explicit hop budget."""
    cyclic = SimulatedAttackGraph(
        assets=(_asset(1), _asset(2), _asset(3), _asset(4, crown=True)),
        relationships=(
            _relationship(1, 2),
            _relationship(2, 3),
            _relationship(3, 1),
            _relationship(3, 4, RelationshipType.ACCESS),
        ),
    )
    assert cyclic.find_shortest_path_to_crown_jewel(UUID(int=1), max_hops=3).hop_count == 3
    with pytest.raises(TopologyNotFoundError):
        cyclic.find_shortest_path_to_crown_jewel(UUID(int=1), max_hops=2)

    dense = SimulatedAttackGraph(
        assets=(_asset(1), _asset(2, crown=True), _asset(3, crown=True), _asset(4)),
        relationships=(
            _relationship(1, 3), _relationship(1, 2), _relationship(1, 4),
            _relationship(4, 2), _relationship(4, 3), _relationship(2, 4),
        ),
    )
    path = dense.find_shortest_path_to_crown_jewel(UUID(int=1))
    assert path.target_asset_id == UUID(int=2)
    assert path.hop_count == 1

    no_crown = SimulatedAttackGraph(assets=(_asset(1), _asset(2)), relationships=(_relationship(1, 2),))
    with pytest.raises(TopologyNotFoundError):
        no_crown.find_shortest_path_to_crown_jewel(UUID(int=1))
    with pytest.raises(TopologyNotFoundError):
        dense.find_shortest_path_to_crown_jewel(UUID(int=99))


def test_risk_score_is_deterministic_for_identical_typed_inputs() -> None:
    """Repeated scoring has no clock, random, or graph-order dependent component."""
    graph = _linear_graph()
    path = graph.find_shortest_path_to_crown_jewel(UUID(int=1))
    scorer = RiskScorer()
    assert scorer.assess(path, graph.assets) == scorer.assess(path, graph.assets)
