{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "art-sim.serviceAccountName" . }}
  labels:
    {{- include "art-sim.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
